<?php

namespace ContainerDLXKxwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JPXCiNFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jPXCiNF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jPXCiNF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'editeurRepository' => ['privates', 'App\\Repository\\EditeurRepository', 'getEditeurRepositoryService', true],
        ], [
            'editeurRepository' => 'App\\Repository\\EditeurRepository',
        ]);
    }
}
