<?php

namespace ContainerDLXKxwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AooLHJoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aooLHJo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aooLHJo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'editeur' => ['privates', '.errored..service_locator.aooLHJo.App\\Entity\\Editeur', NULL, 'Cannot autowire service ".service_locator.aooLHJo": it references class "App\\Entity\\Editeur" but no such service exists.'],
        ], [
            'editeur' => 'App\\Entity\\Editeur',
        ]);
    }
}
