<?php

namespace ContainerDLXKxwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditeurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aooLHJo.App\Entity\Editeur' shared service.
     *
     * @return \App\Entity\Editeur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aooLHJo": it references class "App\\Entity\\Editeur" but no such service exists.');
    }
}
